# Generated by Django 5.2.7 on 2025-12-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Category', models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('RENT', 'Rent'), ('SHOPPING', 'Shopping'), ('BILLS', ' Bills'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
